baseURL = "/"
languageCode = "en-us"
title = "Get Started with AWS for Education"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Get Started"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = '🚀 Get Started'
  homepage_intro = 'AWS for Education is an exciting Quick Start guide aimed to help customers in the Education ecosystem – from startups to educational institutions – to get started with the AWS Cloud.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  enable_anchor_link = false

  [params.homepage_meta_tags]
    meta_description = "AWS for Education is an exciting Quick Start guide aimed to help customers in the Education ecosystem – from startups to educational institutions – to get started with the AWS Cloud."
    meta_og_title = "Amazon Web Services (AWS) for Education"
    meta_og_type = "company"
    meta_og_url = "https://aws.amazon.com/education/"
    meta_og_image = "https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_179x109.png"
    meta_og_description = "Amazon Web Services offers reliable, scalable, and  inexpensive cloud computing services. Free to join, pay only for what you use. AWS for Education is an exciting Quick Start guide aimed to help customers in the Education ecosystem – from startups to educational institutions – to get started with the AWS Cloud."
    meta_twitter_card = "summary"
    meta_twitter_site = "@awscloud"
    meta_twitter_creator = "@awscloud"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
